package com.dongsoop.dongsoop.notification.constant;

public enum NotificationType {

    CHAT,
    NOTICE,
    RECRUITMENT_STUDY_APPLY,
    RECRUITMENT_PROJECT_APPLY,
    RECRUITMENT_TUTORING_APPLY,
    RECRUITMENT_STUDY_APPLY_RESULT,
    RECRUITMENT_PROJECT_APPLY_RESULT,
    RECRUITMENT_TUTORING_APPLY_RESULT,
    TIMETABLE,
    CALENDAR
}
