package com.dongsoop.dongsoop.department;

public enum DepartmentType {

    // 1부터 시작하기 위한 임시값
    NONE,

    // 전체
    UNAFFILIATED,

    // 컴퓨터공학부
    COMPUTER_SOFTWARE,
    ARTIFICIAL_INTELLIGENCE_SOFTWARE,
    WEB_APPLICATION_SOFTWARE,

    // 기계공학부
    MECHANICAL_ENGINEERING,
    MECHANICAL_DESIGN_ENGINEERING,

    // 로봇자동화공학부
    AUTOMATION_ENGINEERING,
    ROBOTICS_SOFTWARE,

    // 전기전자통신공학부
    ELECTRICAL_ENGINEERING,
    SEMICONDUCTOR_ELECTRONICS_ENGINEERING,
    INFORMATION_AND_COMMUNICATION_ENGINEERING,
    FIRE_SAFETY_MANAGEMENT,

    // 생활환경공학부
    CHEMICAL_AND_BIOLOGICAL_ENGINEERING,
    BIO_CONVERGENCE_ENGINEERING,
    ARCHITECTURE,
    INTERIOR_ARCHITECTURE_DESIGN,
    VISUAL_DESIGN,
    AR_VR_CONTENT_DESIGN,

    // 경영학부
    BUSINESS_ADMINISTRATION,
    TAX_ACCOUNTING,
    DISTRIBUTION_MARKETING,
    HOTEL_AND_TOURISM,
    MANAGEMENT_INFORMATION_SYSTEMS,
    BIG_DATA_MANAGEMENT,

    // 자유전공학과
    LIBERAL_ARTS,

    // 교양과
    GENERAL_EDUCATION
}
